services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317'
      - '4318'
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=petorder'
      - 'POSTGRES_PASSWORD=P@ssw0rd@123AA!@#'
      - 'POSTGRES_USER=postgres'
      - "TZ=UTC"
    ports:
      - '5432'
